import type { EncounterCard, EncounterCardId } from '../types.js'

export const ENCOUNTER_DECK: Record<EncounterCardId, EncounterCard> = {
  first_job: {
    id: 'first_job',
    title: 'First Job',
    teaser: 'Your first real paycheck — habits formed now compound for decades.',
    spaceTypes: ['career'],
    domainIds: ['career'],
    scenarioId: 'promotion',
    learningConcept: 'First income allocation',
    weightsByBand: { launch: 35, mid: 2, late: 0 },
  },
  internship: {
    id: 'internship',
    title: 'Internship',
    teaser: 'Short-term income and experience — balance transport, tools, and savings.',
    spaceTypes: ['career', 'education'],
    domainIds: ['career', 'education'],
    scenarioId: 'promotion',
    learningConcept: 'Early career cash flow',
    weightsByBand: { launch: 25, mid: 3, late: 0 },
  },
  job_offer: {
    id: 'job_offer',
    title: 'Job Offer',
    teaser: 'A new employer — compare pay, benefits, and commute before you leap.',
    spaceTypes: ['career'],
    domainIds: ['career'],
    scenarioId: 'promotion',
    learningConcept: 'Opportunity cost of job changes',
    weightsByBand: { launch: 20, mid: 15, late: 5 },
  },
  promotion: {
    id: 'promotion',
    title: 'Promotion',
    teaser: 'A career lift changes your income — how will you allocate it?',
    spaceTypes: ['career'],
    domainIds: ['career'],
    scenarioId: 'promotion',
    learningConcept: 'Income allocation after a raise',
    weightsByBand: { launch: 15, mid: 25, late: 5 },
  },
  executive_promotion: {
    id: 'executive_promotion',
    title: 'Executive Promotion',
    teaser: 'Leadership role, higher pay — and higher stakes for protection and tax planning.',
    spaceTypes: ['career'],
    domainIds: ['career'],
    scenarioId: 'promotion',
    learningConcept: 'High-income planning',
    weightsByBand: { launch: 0, mid: 10, late: 25 },
  },
  retirement_offer: {
    id: 'retirement_offer',
    title: 'Retirement Offer',
    teaser: 'Early retirement package on the table — run the numbers before you sign.',
    spaceTypes: ['career'],
    domainIds: ['career', 'investment'],
    scenarioId: 'promotion',
    learningConcept: 'Retirement readiness',
    weightsByBand: { launch: 0, mid: 5, late: 30 },
  },
  redundancy: {
    id: 'redundancy',
    title: 'Redundancy',
    teaser: 'Role eliminated — severance, benefits, and next steps matter now.',
    spaceTypes: ['career', 'risk'],
    domainIds: ['career'],
    scenarioId: 'protection_stress',
    learningConcept: 'Income shock resilience',
    weightsByBand: { launch: 2, mid: 8, late: 15 },
  },
  consulting_opportunity: {
    id: 'consulting_opportunity',
    title: 'Consulting Opportunity',
    teaser: 'Independent work opens — irregular income needs a different plan.',
    spaceTypes: ['career', 'business'],
    domainIds: ['career', 'business'],
    scenarioId: 'promotion',
    learningConcept: 'Variable income planning',
    weightsByBand: { launch: 3, mid: 10, late: 20 },
  },
  salary_increase: {
    id: 'salary_increase',
    title: 'Salary Increase',
    teaser: 'Your paycheck grows. Lifestyle creep or intentional planning?',
    spaceTypes: ['finance', 'career'],
    domainIds: ['income_finance', 'career'],
    scenarioId: 'promotion',
    learningConcept: 'Lifestyle discipline vs savings',
    weightsByBand: { launch: 15, mid: 20, late: 8 },
  },
  emergency_fund: {
    id: 'emergency_fund',
    title: 'Emergency Fund Gap',
    teaser: 'Unexpected expenses expose how many months you can survive without income.',
    spaceTypes: ['finance'],
    domainIds: ['income_finance'],
    scenarioId: 'protection_stress',
    learningConcept: 'Liquidity and emergency reserves',
    weightsByBand: { launch: 25, mid: 15, late: 10 },
  },
  credit_decision: {
    id: 'credit_decision',
    title: 'Credit Decision',
    teaser: 'A bank offer arrives — understand interest, fees, and your capacity to repay.',
    spaceTypes: ['finance'],
    domainIds: ['income_finance'],
    scenarioId: 'protection_stress',
    learningConcept: 'Responsible borrowing',
    weightsByBand: { launch: 20, mid: 15, late: 8 },
  },
  marriage: {
    id: 'marriage',
    title: 'Marriage',
    teaser: 'Shared goals and protection needs enter the picture.',
    spaceTypes: ['family', 'life_event'],
    domainIds: ['family'],
    scenarioId: 'promotion',
    learningConcept: 'Family financial planning',
    weightsByBand: { launch: 8, mid: 25, late: 10 },
  },
  business_opportunity: {
    id: 'business_opportunity',
    title: 'Business Opportunity',
    teaser: 'A side venture opens — capital, risk, and cash flow trade-offs.',
    spaceTypes: ['business', 'opportunity'],
    domainIds: ['business'],
    scenarioId: 'promotion',
    learningConcept: 'Entrepreneurial cash flow',
    weightsByBand: { launch: 15, mid: 20, late: 12 },
  },
  vehicle_breakdown: {
    id: 'vehicle_breakdown',
    title: 'Vehicle Breakdown',
    teaser: 'An unexpected repair strains this month’s budget.',
    spaceTypes: ['risk'],
    domainIds: ['lifestyle', 'income_finance'],
    scenarioId: 'protection_stress',
    learningConcept: 'Emergency fund readiness',
    weightsByBand: { launch: 10, mid: 12, late: 8 },
  },
  medical_expense: {
    id: 'medical_expense',
    title: 'Medical Expense',
    teaser: 'Health costs surface — protection gaps matter.',
    spaceTypes: ['health', 'risk'],
    domainIds: ['health'],
    scenarioId: 'protection_stress',
    learningConcept: 'Health protection planning',
  },
  annual_checkup: {
    id: 'annual_checkup',
    title: 'Annual Checkup',
    teaser: 'Routine care reveals small gaps in your health budget and coverage.',
    spaceTypes: ['health'],
    domainIds: ['health'],
    scenarioId: 'protection_stress',
    learningConcept: 'Preventive care vs cash flow',
    weightsByBand: { launch: 15, mid: 20, late: 18 },
  },
  minor_injury: {
    id: 'minor_injury',
    title: 'Minor Injury',
    teaser: 'An accident this year — out-of-pocket costs and time off work add up.',
    spaceTypes: ['health'],
    domainIds: ['health'],
    scenarioId: 'protection_stress',
    learningConcept: 'Health emergency readiness',
    weightsByBand: { launch: 20, mid: 18, late: 15 },
  },
  hospitalization: {
    id: 'hospitalization',
    title: 'Hospitalization',
    teaser: 'A serious health event tests your savings, HMO, and family plan.',
    spaceTypes: ['health'],
    domainIds: ['health'],
    scenarioId: 'protection_stress',
    learningConcept: 'Major medical protection',
    weightsByBand: { launch: 8, mid: 15, late: 25 },
  },
  first_home: {
    id: 'first_home',
    title: 'First Home',
    teaser: 'Down payment, loan terms, and monthly housing cost enter the picture.',
    spaceTypes: ['finance'],
    domainIds: ['housing'],
    scenarioId: 'promotion',
    learningConcept: 'Housing affordability',
    weightsByBand: { launch: 20, mid: 15, late: 5 },
  },
  rent_increase: {
    id: 'rent_increase',
    title: 'Rent Increase',
    teaser: 'Landlord raises rent — rebalance cash flow or rethink location.',
    spaceTypes: ['finance'],
    domainIds: ['housing'],
    scenarioId: 'protection_stress',
    learningConcept: 'Housing cost shocks',
    weightsByBand: { launch: 25, mid: 20, late: 10 },
  },
  pagibig_loan: {
    id: 'pagibig_loan',
    title: 'Pag-IBIG Housing Loan',
    teaser: 'Government-backed housing finance — amortization vs other goals.',
    spaceTypes: ['finance'],
    domainIds: ['housing', 'government'],
    scenarioId: 'promotion',
    learningConcept: 'Long-term housing debt',
    weightsByBand: { launch: 10, mid: 25, late: 12 },
  },
  job_loss: {
    id: 'job_loss',
    title: 'Job Loss Risk',
    teaser: 'Income uncertainty — how resilient is your plan?',
    spaceTypes: ['career', 'risk'],
    domainIds: ['career', 'income_finance'],
    scenarioId: 'protection_stress',
    learningConcept: 'Income protection',
    weightsByBand: { launch: 5, mid: 12, late: 10 },
  },
  economic_boom: {
    id: 'economic_boom',
    title: 'Economic Boom',
    teaser: 'Markets rise — opportunity with discipline.',
    spaceTypes: ['finance', 'investment'],
    domainIds: ['investment', 'income_finance'],
    scenarioId: 'promotion',
    learningConcept: 'Goal acceleration',
    weightsByBand: { launch: 8, mid: 15, late: 12 },
  },
  inflation: {
    id: 'inflation',
    title: 'Inflation',
    teaser: 'Purchasing power erodes — adjust spending and protection.',
    spaceTypes: ['finance'],
    domainIds: ['income_finance', 'lifestyle'],
    scenarioId: 'protection_stress',
    learningConcept: 'Real vs nominal planning',
    weightsByBand: { launch: 10, mid: 15, late: 12 },
  },
  education: {
    id: 'education',
    title: 'Education Investment',
    teaser: 'Upskilling costs compete with other goals.',
    spaceTypes: ['education'],
    domainIds: ['education'],
    scenarioId: 'promotion',
    learningConcept: 'Education goal funding',
    weightsByBand: { launch: 30, mid: 10, late: 3 },
  },
  tax_season: {
    id: 'tax_season',
    title: 'Taxes & BIR Filing',
    teaser: 'Annual tax compliance — deductions, refunds, and cash timing.',
    spaceTypes: ['finance'],
    domainIds: ['government'],
    scenarioId: 'protection_stress',
    learningConcept: 'Tax planning basics',
    weightsByBand: { launch: 8, mid: 15, late: 12 },
  },
  relationship_finances: {
    id: 'relationship_finances',
    title: 'Relationship Finances',
    teaser: 'Money conversations with a partner or family — align values and accounts.',
    spaceTypes: ['family'],
    domainIds: ['family'],
    scenarioId: 'promotion',
    learningConcept: 'Shared financial goals',
    weightsByBand: { launch: 12, mid: 20, late: 10 },
  },
  milestone: {
    id: 'milestone',
    title: 'Life Milestone',
    teaser: 'A major life marker — revisit goals and protection.',
    spaceTypes: ['milestone', 'life_event'],
    domainIds: ['milestone'],
    scenarioId: 'promotion',
    learningConcept: 'Goal portfolio review',
    weightsByBand: { launch: 8, mid: 12, late: 22 },
  },
  legacy_planning: {
    id: 'legacy_planning',
    title: 'Legacy Planning',
    teaser: 'Estate, dependents, and what you leave behind — plan with intention.',
    spaceTypes: ['milestone', 'life_event'],
    domainIds: ['milestone', 'investment'],
    scenarioId: 'promotion',
    learningConcept: 'Wealth transfer and legacy',
    weightsByBand: { launch: 0, mid: 5, late: 30 },
  },
  rest: {
    id: 'rest',
    title: 'Rest & Recharge',
    teaser: 'A quieter season — maintain discipline without new income.',
    spaceTypes: ['rest'],
    domainIds: ['lifestyle'],
    scenarioId: 'promotion',
    learningConcept: 'Maintaining financial habits',
    weightsByBand: { launch: 10, mid: 8, late: 10 },
  },
  bonus: {
    id: 'bonus',
    title: 'Bonus Windfall',
    teaser: 'Unexpected cash — debt, goals, or lifestyle?',
    spaceTypes: ['bonus'],
    domainIds: ['income_finance'],
    scenarioId: 'promotion',
    learningConcept: 'Windfall allocation',
    weightsByBand: { launch: 12, mid: 15, late: 10 },
  },
  community: {
    id: 'community',
    title: 'Community Giving',
    teaser: 'Generosity meets budget — plan giving intentionally.',
    spaceTypes: ['community'],
    domainIds: ['community'],
    scenarioId: 'promotion',
    learningConcept: 'Values-based budgeting',
    weightsByBand: { launch: 10, mid: 12, late: 15 },
  },
  investment: {
    id: 'investment',
    title: 'Investment Review',
    teaser: 'Portfolio check-in — growth vs protection balance.',
    spaceTypes: ['investment'],
    domainIds: ['investment'],
    scenarioId: 'promotion',
    learningConcept: 'Wealth building discipline',
    weightsByBand: { launch: 5, mid: 15, late: 28 },
  },
}

export function getEncounterCard(id: EncounterCardId): EncounterCard {
  const card = ENCOUNTER_DECK[id]
  if (!card) throw new Error(`Unknown encounter card: ${id}`)
  return card
}
