import type { BoardConfig } from '../types/board-config.js'

/** Default SPIKE LIFE board — change this JSON to reshape the game without touching React. */
export const DEFAULT_BOARD_CONFIG: BoardConfig = {
  id: 'spike-life-default',
  title: 'Financial Life Journey',
  layout: 'rounded-rectangle',
  layoutOptions: {
    padding: 0.09,
    cornerRadius: 0.13,
  },
  maxPlayers: 6,
  spaces: [
    {
      id: 'career-lift',
      title: 'Career Lift',
      category: 'career',
      color: '#E84855',
      icon: 'briefcase',
      description: 'Advance your career path',
      boardIndex: 0,
      encounterId: 'promotion',
    },
    {
      id: 'paycheck',
      title: 'Paycheck',
      category: 'finance',
      color: '#3B82F6',
      icon: 'wallet',
      boardIndex: 1,
      encounterId: 'salary_increase',
    },
    {
      id: 'opportunity',
      title: 'Opportunity',
      category: 'opportunity',
      color: '#10B981',
      icon: 'sparkles',
      boardIndex: 2,
      encounterId: 'business_opportunity',
    },
    {
      id: 'unexpected',
      title: 'Unexpected',
      category: 'risk',
      color: '#F97316',
      icon: 'alert',
      boardIndex: 3,
      encounterId: 'vehicle_breakdown',
    },
    {
      id: 'family',
      title: 'Family',
      category: 'family',
      color: '#EC4899',
      icon: 'heart',
      boardIndex: 4,
      encounterId: 'marriage',
    },
    {
      id: 'health',
      title: 'Health',
      category: 'health',
      color: '#14B8A6',
      icon: 'medical',
      boardIndex: 5,
      encounterId: 'medical_expense',
    },
    {
      id: 'business',
      title: 'Business',
      category: 'business',
      color: '#8B5CF6',
      icon: 'building',
      boardIndex: 6,
      encounterId: 'business_opportunity',
    },
    {
      id: 'invest',
      title: 'Invest',
      category: 'investment',
      color: '#EAB308',
      icon: 'chart',
      boardIndex: 7,
      encounterId: 'investment',
    },
    {
      id: 'learn',
      title: 'Learn',
      category: 'education',
      color: '#6366F1',
      icon: 'book',
      boardIndex: 8,
      encounterId: 'education',
    },
    {
      id: 'milestone',
      title: 'Milestone',
      category: 'life_event',
      color: '#A855F7',
      icon: 'star',
      boardIndex: 9,
      encounterId: 'milestone',
    },
    {
      id: 'rest',
      title: 'Rest',
      category: 'rest',
      color: '#94A3B8',
      icon: 'moon',
      boardIndex: 10,
      encounterId: 'rest',
    },
    {
      id: 'bonus',
      title: 'Bonus',
      category: 'bonus',
      color: '#22C55E',
      icon: 'gift',
      boardIndex: 11,
      encounterId: 'bonus',
    },
    {
      id: 'community',
      title: 'Community',
      category: 'community',
      color: '#06B6D4',
      icon: 'users',
      boardIndex: 12,
      encounterId: 'community',
    },
    {
      id: 'inflation',
      title: 'Inflation',
      category: 'finance',
      color: '#2563EB',
      icon: 'trending',
      boardIndex: 13,
      encounterId: 'inflation',
    },
    {
      id: 'job-risk',
      title: 'Job Risk',
      category: 'risk',
      color: '#EA580C',
      icon: 'alert',
      boardIndex: 14,
      encounterId: 'job_loss',
    },
    {
      id: 'boom',
      title: 'Boom',
      category: 'milestone',
      color: '#818CF8',
      icon: 'star',
      boardIndex: 15,
      encounterId: 'economic_boom',
    },
  ],
}

export const SPACE_CATEGORY_LEGEND = [
  { category: 'career' as const, label: 'Career', color: '#E84855' },
  { category: 'finance' as const, label: 'Finance', color: '#3B82F6' },
  { category: 'opportunity' as const, label: 'Opportunity', color: '#10B981' },
  { category: 'risk' as const, label: 'Risk', color: '#F97316' },
  { category: 'family' as const, label: 'Family', color: '#EC4899' },
  { category: 'health' as const, label: 'Health', color: '#14B8A6' },
  { category: 'business' as const, label: 'Business', color: '#8B5CF6' },
  { category: 'investment' as const, label: 'Investment', color: '#EAB308' },
  { category: 'education' as const, label: 'Education', color: '#6366F1' },
  { category: 'life_event' as const, label: 'Life Event', color: '#A855F7' },
  { category: 'milestone' as const, label: 'Milestone', color: '#818CF8' },
  { category: 'rest' as const, label: 'Rest', color: '#94A3B8' },
  { category: 'bonus' as const, label: 'Bonus', color: '#22C55E' },
  { category: 'community' as const, label: 'Community', color: '#06B6D4' },
]
