export const WEEK5_DAY1_ID = 'day-segment-1-week-5-day-1';
export const WEEK5_DAY2_ID = 'day-segment-1-week-5-day-2';

export const WEEK5_DAY1_DECK_URL =
  '/api/coach/faculty-deck/segment-1/week-5/day-1/faculty-deck-01.pdf';

export const WEEK5_DEFAULT_JOURNEY_STAGES = [
  { id: 'awareness', title: 'Awareness', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'first-contact', title: 'First Contact', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'discovery', title: 'Discovery', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'assessment', title: 'Financial Assessment', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'recommendation', title: 'Recommendation', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'decision', title: 'Decision', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'onboarding', title: 'Onboarding', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'continuing', title: 'Continuing Service', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'referral', title: 'Referral', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
  { id: 'review', title: 'Review', description: '', emotion: '', advisorAction: '', platformSupport: '', risk: '' },
];

export const WEEK5_DAY1_SECTIONS = [
  {
    id: 'venture-sentence',
    number: 1,
    title: 'The Venture in One Sentence',
    prompt: 'Describe your venture in one clear sentence.',
    coaching: [
      'Who do you serve?',
      'What problem do you solve?',
      'What do you help them achieve?',
      'How is your approach different?',
      'Can someone understand the business without further explanation?',
    ],
    fields: [{ id: 'ventureOneSentence', label: 'Venture in one sentence', type: 'textarea' }],
  },
  {
    id: 'customer',
    number: 2,
    title: 'The Customer',
    prompt: 'Who exactly is your primary customer?',
    coaching: [
      'What demographic or life stage do they belong to?',
      'What situation are they currently experiencing?',
      'What financial concern is most urgent for them?',
      'What makes them different from the general market?',
      'Who is not part of your target market?',
    ],
    fields: [
      { id: 'customerSegmentName', label: 'Customer segment name', type: 'text' },
      { id: 'customerProfile', label: 'Short profile', type: 'textarea' },
      { id: 'customerLifeStage', label: 'Life stage', type: 'text' },
      { id: 'customerIncomeContext', label: 'Income or economic context', type: 'text' },
      { id: 'customerLocation', label: 'Location or community', type: 'text' },
      { id: 'customerFinancialSituation', label: 'Current financial situation', type: 'textarea' },
      { id: 'customerKeyBehavior', label: 'Key behavior', type: 'textarea' },
      { id: 'customerExclusions', label: 'Exclusions / non-target customers', type: 'textarea' },
      { id: 'customerNotes', label: 'Supporting notes', type: 'textarea' },
    ],
  },
  {
    id: 'problem',
    number: 3,
    title: 'The Problem',
    prompt: 'What important problem are you solving?',
    coaching: [
      'What is happening in the customer’s life?',
      'Why does the problem matter?',
      'What happens when it remains unresolved?',
      'How often does this problem occur?',
      'What emotional, financial, or practical consequence does it create?',
      'Is this a real problem or only an interesting idea?',
    ],
    fields: [
      { id: 'problemStatement', label: 'Problem statement', type: 'textarea' },
      { id: 'problemRootCause', label: 'Root cause', type: 'textarea' },
      { id: 'problemCurrentConsequence', label: 'Current consequence', type: 'textarea' },
      { id: 'problemLongTermConsequence', label: 'Long-term consequence', type: 'textarea' },
      { id: 'problemFrequency', label: 'Frequency', type: 'text' },
      { id: 'problemSeverity', label: 'Severity', type: 'text' },
      { id: 'problemEvidence', label: 'Evidence', type: 'textarea' },
      { id: 'problemCustomerQuote', label: 'Direct customer quote', type: 'textarea' },
      { id: 'problemNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'validation',
    number: 4,
    title: 'Validation Evidence',
    prompt: 'What evidence shows that this problem is real?',
    coaching: [
      'How many people did you speak with?',
      'What patterns appeared repeatedly?',
      'What surprised you?',
      'What did customers already try?',
      'What frustrated them?',
      'What evidence contradicts your assumptions?',
      'What still needs to be validated?',
    ],
    fields: [
      { id: 'validationInterviewCount', label: 'Number of interviews', type: 'text' },
      { id: 'validationCommonPattern', label: 'Common pattern', type: 'textarea' },
      { id: 'validationStrongestQuote', label: 'Strongest quote', type: 'textarea' },
      { id: 'validationSurprise', label: 'Surprising insight', type: 'textarea' },
      { id: 'validationAlternatives', label: 'Existing alternatives', type: 'textarea' },
      { id: 'validationUnvalidated', label: 'Unvalidated assumption', type: 'textarea' },
      { id: 'validationNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'client-promise',
    number: 5,
    title: 'The Client Promise',
    prompt: 'What meaningful outcome do you promise to help the client achieve?',
    coaching: [
      'What changes for the client?',
      'What does success look like?',
      'Why should the client care?',
      'Is the promise believable?',
      'Is it specific enough to remember?',
      'Does it connect directly to the customer problem?',
    ],
    fields: [
      { id: 'clientPromise', label: 'Client promise', type: 'textarea' },
      { id: 'clientDesiredOutcome', label: 'Desired customer outcome', type: 'textarea' },
      { id: 'clientReasonToBelieve', label: 'Reason to believe', type: 'textarea' },
      { id: 'clientDifferentiator', label: 'What makes it different', type: 'textarea' },
      { id: 'clientPromiseNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'client-experience',
    number: 6,
    title: 'The Client Experience',
    prompt: 'How will the customer experience your service from first contact to continuing relationship?',
    coaching: [
      'How will the customer first discover you?',
      'What happens during the first conversation?',
      'How will you understand their needs?',
      'How will recommendations be presented?',
      'What happens after the initial transaction?',
      'How will you build trust over time?',
      'Where could the customer experience fail?',
    ],
    kind: 'journey',
  },
  {
    id: 'winning-strategy',
    number: 7,
    title: 'The Winning Strategy',
    prompt: 'Why will this venture succeed in its chosen market?',
    coaching: [
      'How will you reach the market?',
      'Why will customers trust you?',
      'What advantage comes from the AIA platform?',
      'What will competitors find difficult to copy?',
      'What activity must happen consistently?',
      'What is the biggest execution risk?',
      'What is your response if the first strategy does not work?',
    ],
    fields: [
      { id: 'strategyMarketEntry', label: 'Market entry strategy', type: 'textarea' },
      { id: 'strategyTrust', label: 'Trust strategy', type: 'textarea' },
      { id: 'strategyAcquisition', label: 'Acquisition strategy', type: 'textarea' },
      { id: 'strategyPartnership', label: 'Partnership strategy', type: 'textarea' },
      { id: 'strategyAiaAdvantage', label: 'AIA platform advantage', type: 'textarea' },
      { id: 'strategyCompetitive', label: 'Competitive advantage', type: 'textarea' },
      { id: 'strategyCoreActivity', label: 'Core activity', type: 'textarea' },
      { id: 'strategyBiggestRisk', label: 'Biggest risk', type: 'textarea' },
      { id: 'strategyRiskResponse', label: 'Risk response', type: 'textarea' },
      { id: 'strategyNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'revenue-logic',
    number: 8,
    title: 'Revenue Logic',
    prompt: 'How does the venture create revenue?',
    coaching: [
      'What customer activity leads to revenue?',
      'How many prospects are needed?',
      'How many discovery meetings are needed?',
      'How many solution presentations are needed?',
      'How many clients are expected?',
      'What is the assumed commission or revenue per client?',
      'Are the assumptions realistic?',
      'What happens when conversion is lower than expected?',
    ],
    kind: 'revenue',
  },
  {
    id: 'growth-leadership',
    number: 9,
    title: 'Growth and Leadership Logic',
    prompt: 'How will the venture grow beyond the effort of one person?',
    coaching: [
      'When should the team begin recruiting?',
      'What kind of people should join?',
      'How will new people be developed?',
      'How does team growth affect market reach?',
      'How does leadership create leverage?',
      'What systems are needed before scaling?',
      'What should remain founder-led?',
      'What should eventually be delegated?',
    ],
    fields: [
      { id: 'growthYear1Team', label: 'Year 1 team size', type: 'text' },
      { id: 'growthYear2Team', label: 'Year 2 team size', type: 'text' },
      { id: 'growthYear3Team', label: 'Year 3 team size', type: 'text' },
      { id: 'growthRecruitmentProfile', label: 'Recruitment profile', type: 'textarea' },
      { id: 'growthRecruitmentChannels', label: 'Recruitment channels', type: 'textarea' },
      { id: 'growthDevelopment', label: 'Development approach', type: 'textarea' },
      { id: 'growthLeadershipMilestones', label: 'Leadership milestones', type: 'textarea' },
      { id: 'growthMarketReach', label: 'Expected market reach', type: 'textarea' },
      { id: 'growthTeamProduction', label: 'Expected team production', type: 'textarea' },
      { id: 'growthSystemsRequired', label: 'Systems required', type: 'textarea' },
      { id: 'growthNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'fec-review',
    number: 10,
    title: 'Financial Entrepreneurship Canvas Review',
    prompt: 'Review and refine your complete FEC before the pitch.',
    kind: 'fec',
  },
  {
    id: 'weakest-part',
    number: 11,
    title: 'The Weakest Part',
    prompt: 'What is currently the weakest part of your venture?',
    coaching: [
      'Which assumption would the panel challenge first?',
      'Which number is least supported?',
      'Which section is still too broad?',
      'Which part does not connect with the rest of the business?',
      'What must be improved before the final pitch?',
    ],
    fields: [
      { id: 'weakestSection', label: 'Weakest section', type: 'text' },
      { id: 'weakestWhy', label: 'Why it is weak', type: 'textarea' },
      { id: 'weakestMustChange', label: 'What must change', type: 'textarea' },
      { id: 'weakestOwner', label: 'Person responsible', type: 'text' },
      { id: 'weakestTargetDate', label: 'Target completion date', type: 'text' },
      { id: 'weakestNotes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'reflection',
    number: 12,
    title: 'Day 1 Reflection',
    prompt: 'Capture what shifted today.',
    kind: 'reflection',
    reflectionPrompts: [
      'What became clearer today?',
      'What assumption did you change?',
      'What part of the venture became stronger?',
      'What still needs work?',
      'What will your squad complete before the next session?',
    ],
  },
];

export const WEEK5_DAY2_PITCH_SECTIONS_DEFAULT = [
  'The Customer',
  'The Problem',
  'Evidence the Problem Is Real',
  'The Venture',
  'The Client Promise',
  'The Client Experience',
  'Why AIA Is the Platform',
  'The Business Engine',
  'The Revenue Model',
  'The Growth and Leadership Strategy',
  'Three-Year Projection',
  'Why This Venture Will Win',
  'The Ask or Commitment',
  'Closing Message',
];

export const WEEK5_DAY2_PANEL_QUESTIONS_DEFAULT = [
  'Why is this problem important enough to solve?',
  'What evidence shows the customer actually wants this?',
  'Why would customers trust you?',
  'How will you reach the first one hundred prospects?',
  'What happens if your conversion rate is lower?',
  'Why is the revenue assumption realistic?',
  'What prevents another advisor from copying this?',
  'What role does AIA play?',
  'How will this grow beyond the founders?',
  'What is the biggest risk?',
  'What will you do in the first ninety days?',
  'Why should we believe this squad can execute?',
];

export const WEEK5_DAY2_READINESS_ITEMS = [
  'Customer is clear',
  'Problem is specific',
  'Evidence is visible',
  'Venture is easy to understand',
  'Client promise is compelling',
  'Business model is credible',
  'Revenue logic is consistent',
  'Growth logic is realistic',
  'Leadership strategy is explained',
  'AIA platform role is clear',
  'Three-year projection is supported',
  'Squad roles are clear',
  'Opening is strong',
  'Closing is memorable',
  'Panel questions are prepared',
  'Timing has been rehearsed',
];
